version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  agent:
    build: ../devil
    ports:
      - "5000:5000"
    env_file: 
      - ../devil/.env
    privileged: true
    volumes:
      - /:/host:ro  # Read-only access to entire host filesystem,modify this to allow full Access
    depends_on:
      - redis

  web:
    build: ../frontend
    ports:
      - "56789:56789"
    

volumes:
  redis_data:

